### ISSUE TITLE
Buildroot 2023.02 + buildroot-external-microchip fails with ecc_key error

### ISSUE THREAD

**Issue by Jarscott1** [linux4microchip/buildroot-external-microchip#10]
I am trying to follow the README instructions in this repository to build busybox buildroot, and keep coming up unsuccessful.

Setting the BR2_EXTERNAL to this repo, using icicle_defconfig and running make from buildroot eventually exits with the following error (in what appears to be the dropbear step):

[make_output.txt](https://github.com/linux4microchip/buildroot-external-microchip/files/13358334/make_output.txt)

Feel free to reach out if you need further context. Thanks!

**Comment by jamiegibbons** [comment]
Hi @Jarscott1, could you check which Buildroot version you are using? Unfortunately, there is an error in our documentation that was updated recently. Could you ensure you are building with version 2022.02 instead of version 2023.02 please? In version 2023.02 this error shows up due to changes made in an updated version of Dropbear. We are working on this issue. In the meantime, Buildroot version 2022.02 should work for you.

**Comment by Jarscott1** [comment]
Thanks, I verified 2022.02 built successfully, and 2023.02 didn't, so I will revert to the 2022.02 version for now.
