### ISSUE TITLE
How to reduce the size of sdcard.img as small as possible?

### ISSUE THREAD

**Issue by XianluoCat** [linux4microchip/buildroot-external-microchip#12]
The original sdcard.img size about 7.28G, I had tried to chang the Filesystem images--> exact size from 7558959K to 163840K, this operation make sdcard.img reduce to 243M, but it still too large. I want to delete the example in /opt/microchip， so I disable External options-->mpfs_example, but it doesn't work, I also tried to delete buildroot/output/target/opt/microchip, the result is the same. 
May be the file /board/xxx/genimage.cfg can reduce the second partition, but I can not find which one.

**Comment by XianluoCat** [comment]
I find the genimage.cfg file in buildroot-external-microchip/board/microchip/icicle, so I change the image boot.vfat size to 30M, it really work. 
partition uboot: payload.bin is only 741KB, but there is 8MB to contain it.
partition kernel: how to make the mpfs_icicle.itb smaller and what is in it?
partition root: how can I edit the rootfs.cpio?

**Comment by jamiegibbons** [comment]
Hi @XianluoCat,

To remove the Linux PolarFire SoC examples from the target root filesystem you can simply remove the inclusion of it in the defconfig. i.e. remove `BR2_PACKAGE_MPFS_EXAMPLES=y` from the icicle_defconfig. For this change to be effective, you must do a clean build. This will allow the mpfs examples package to then not be built and it will not be included in the target file system. i.e. run `make clean`, `BR2_EXTERNAL=../buildroot-external-microchip/ make icicle_defconfig`, `make`, after you have removed that kconfig option from your defconfig.

The `genimage.cfg` located in `buildroot-external-microchip/board/microchip/icicle/` is the corresponding configuration file for the image that is generation by the `icicle_defconfig`. This file allows you to determine the partitions of your `sdcard.img`. You can change the size of a partition using the `size` property. For example, changing the size property of the boot.vfat partition (line 13) will change the size of this partition. However, you must be careful when changing this property as you must ensure that it is large enough to fit the contents of that partition. Note that if the size property is not used, as you can see in other partitions, the size of the partition image is used. You can find more information about this file and the properties you can use to get the desired outcome for your partitions [here](https://github.com/pengutronix/genimage#the-image-section).

`partition uboot`: This partition contains the Hart Software Services (HSS) payload generator binary. The payload defines the entry point and payloads for each hart - including the U-Boot payload. In the AMP configuration, it also loads the AMP examples binary.

`partition kernel`: The `mpfs_icicle.itb` is the FIT image generated by the build. i.e. it contains the compressed kernel image (containing the initramfs), the base device tree and any additional overlays. 

`partition root`: This is your filesystem that is generated by the build.

As mentioned above, if you want to change the size of the partition, use the `size` property in the `genimage.cfg`. If you want to change the size of contents of the partition, you must change the contents of any of those components. e.g. you could remove some of the packages included in the `icicle_defconfig` that you do not need for your application or remove other features using the kernel kconfigs or other buildroot kconfigs. Warning: to do any of this, you must ensure you know what you are doing and exactly what you are removing, if you are not careful, you could break the build/image.

Please note: The example defconfigs provided in the `configs/icicle*` directory are provided as robust examples to give users easy access to features that they want. As a result, the images that are created from these defconfigs are likely larger, and more feature rich than they need to be for any one persons application. Therefore, it is advised that when developing the system for your application, you customise this defconfig and the supporting files (`board/microchip/icicle*`) and packages to suit your needs.

Hope this helps.

**Comment by XianluoCat** [comment]
Hi,@jamiegibbons, the mpfs_example finally disappear when I clean and rebuild the build, the system banner as so on. But when I delete the uboot partition and disable HSS_PAYLOAD_GENERATOR(I forget disable it at first, then i rebuild but not clean it ) the hss occur the error: Unable to find partition for GUID 21686148-6449-6e6f-744e656564454649
.
There is another problem, I try to reduce the size of img because I want to download the img to emmc without usbdmsc method, we make a new board with this cpu, but the project cannot allow the circuit direct to emmc, so I have to download the img with Y-modem or something else, but Y-modem need the binary file, can the buildroot or some other tools make this?

**Comment by jamiegibbons** [comment]
Hi @XianluoCat, this error you are seeing in the HSS console is because the HSS is looking for this partition in order to load the U-Boot binary. I was misleading when I explained this in my previous message and have since fixed this in the original post to avoid further confusion, my apologies. While this partition does contain the Hart Software Services (HSS) payload generator binary. What I should have mentioned was, the payload in this instance is used to define the entry points for each hart and load the executable. What I meant was you can remove whatever features you are not using **in your system**. I do not know anything about the system you are developing for or the purpose/requirements and therefore, cannot advise on what you do and do not need - without this information. However, if you are using an icicle kit and using our default files and configurations, you need this functionality for the U-Boot payload binary (- as this is the bootloader we use). Please see [our HSS documentation](https://github.com/polarfire-soc/polarfire-soc-documentation/blob/master/hss-and-u-boot/hss-payloads.md) for more information on HSS. 

This is not a feature we currently support with our configurations. However, you can find more information about how to use this feature with Buildroot online. I have seen there is support for the lrzsz package in Buildroot which should be helpful for you. You can search for this package in the Buildroot menu, i.e. `make menuconfig`. You can then enable this package for y-modem support. `BR2_PACKAGE_LRZSZ=y`. If you need more information on this to get it set up for protocol you could have a look at some old patch submissions [here](https://patchwork.ozlabs.org/project/buildroot/patch/22856a59ac4af71690638f10f2117cd83c853928.1527184278.git.baruch@tkos.co.il/) and [here](http://lists.busybox.net/pipermail/buildroot/2018-May/524657.html).
